/* MathModel Workbench — data first, local API only. */
(() => {
  const STAGES=['S0','S1','S2','S3','S4','S5','S6','S7','S8'];
  const TITLES={S0:'输入接纳',S1:'问题分析',S2:'模型路线',S3:'数据与可视化',S4:'可复现代码',S5:'真实执行',S6:'证据门禁',S7:'正式写作',S8:'格式与渲染检查'};
  const LABEL={pending:'待执行',running:'运行中',passed:'已通过',failed:'失败',stale:'已失效',validating:'待验证',awaiting_validation:'待验证',cancelled:'已取消'};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const token=new URLSearchParams(location.search).get('token')||''; const api=p=>`${p}${p.includes('?')?'&':'?'}token=${encodeURIComponent(token)}`;
  let state={project:'MathModel project',stage:'S0',status:'pending',stages:[],history:[],artifacts:[],jobs:[]}, view='overview', selectedFile=null;
  const fmt=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});};
  const badge=s=>{s=['running','passed','failed','stale','pending','validating','awaiting_validation','cancelled'].includes(s)?s:'pending';return `<span class="badge ${s}"><i></i>${LABEL[s]||s}</span>`};
  function normalize(s){const arr=Array.isArray(s.stages)?s.stages:[];return STAGES.map((code,i)=>{const x=arr.find(a=>(a.code||a.stage)===code)||{};let status=x.status||'pending';if(!arr.length){const idx=STAGES.indexOf(s.stage||'S0');status=i<idx?'passed':i===idx?(s.status||'pending'):'pending';}return {code,name:TITLES[code],status,message:x.message||'',updated_at:x.updated_at};});}
  function artifacts(){return Array.isArray(state.artifacts)?state.artifacts:[];}
  function pathParts(path){return String(path||'').replaceAll('\\','/').split('/').filter(Boolean);}
  function renderTree(){const tree=document.getElementById('file-tree');const files=artifacts().map(a=>typeof a==='string'?{path:a,kind:'artifact'}:{path:a.path||a.name,id:a.id,kind:a.kind||a.type||'artifact'}).filter(a=>a.path);const groups={题目:[],代码:[],结果:[],论文:[]}; files.forEach(f=>{const p=f.path.toLowerCase();const g=p.includes('paper')||p.includes('doc')||p.includes('pdf')?'论文':p.includes('result')||p.includes('figure')||p.includes('table')?'结果':p.endsWith('.py')||p.endsWith('.ipynb')?'代码':'题目';groups[g].push(f);});tree.innerHTML=Object.entries(groups).filter(([,xs])=>xs.length).map(([name,xs])=>`<div class="tree-group"><button class="folder" aria-expanded="true"><span class="chevron">⌄</span><span class="folder-icon">▱</span>${name}<small>${xs.length}</small></button><div class="tree-children">${xs.map(f=>`<button class="file" data-file="${esc(f.id||f.path)}"><span class="file-icon">${f.kind==='figure'?'◌':f.kind==='table'?'▦':'·'}</span><span>${esc(pathParts(f.path).slice(-1)[0])}</span></button>`).join('')}</div></div>`).join('')||`<div class="tree-empty">项目产物将在这里出现<br><span>运行预检或模型任务后自动同步</span></div>`;}
  function stageTable(){return `<div class="stage-table">${state.stages.map(x=>`<div class="stage-line ${x.code===state.stage?'current':''}"><span class="stage-code">${x.code}</span><span class="stage-title">${x.name}</span><span class="stage-evidence">${x.message?esc(x.message):'—'}</span>${badge(x.status)}</div>`).join('')}</div>`;}
  function eventList(){const es=Array.isArray(state.history)?state.history.slice().reverse().slice(0,8):[];return es.length?`<div class="event-list">${es.map(e=>`<div class="event"><span class="event-time">${fmt(e.timestamp||e.created_at)}</span><span class="event-code">${esc(e.stage||'SYS')}</span><span>${esc(e.message||e.current_task||LABEL[e.status]||'活动')}</span></div>`).join('')}</div>`:`<div class="empty">暂无活动记录</div>`;}
  function filePreview(){if(!selectedFile)return `<div class="empty hero-empty"><strong>选择一个文件开始</strong><span>从左侧项目树打开题目、代码或运行产物</span></div>`;const a=artifacts().find(x=>(x.id||x.path)===selectedFile);return `<div class="file-preview"><div class="preview-head"><span class="mono">${esc(a?.path||selectedFile)}</span><button class="subtle-btn">只读</button></div><pre>${esc(state.code_preview||'正在读取登记产物…')}</pre></div>`;}
  async function openArtifact(id){selectedFile=id;state.code_preview='正在读取登记产物…';view='code';render();try{const r=await fetch(api('/api/artifact/'+encodeURIComponent(id)),{cache:'no-store'});if(!r.ok)throw Error(r.status);const type=r.headers.get('content-type')||'';state.code_preview=type.includes('text')||type.includes('json')||type.includes('javascript')?await r.text():'二进制产物已登记。请在论文与交付页预览或下载。';}catch(e){state.code_preview=`读取失败：${e.message}`;}render();}
  function renderOverview(){const s=state.stages.find(x=>x.code===state.stage)||state.stages[0];document.getElementById('app').innerHTML=`<div class="page-title"><div><span class="eyebrow">WORKSPACE / OVERVIEW</span><h1>${esc(state.project||'MathModel project')}</h1><p>${esc(state.message||'对话驱动建模，工作台同步真实证据。')}</p></div><div class="title-status">${badge(s?.status||state.status)}</div></div><div class="metric-strip"><div><span class="metric-label">验证阶段</span><strong>${state.stages.filter(x=>x.status==='passed').length}<small>/ 9</small></strong></div><div><span class="metric-label">当前阶段</span><strong>${s?.code||'S0'} <small>${esc(s?.name||'输入接纳')}</small></strong></div><div><span class="metric-label">最近更新</span><strong>${fmt(state.updated_at)}</strong></div></div><div class="split-grid"><section class="panel panel-wide"><div class="panel-head"><div><h2>建模流程</h2><span>验证状态 · 证据链</span></div><button class="subtle-btn" data-view="workflow">查看全部 →</button></div>${stageTable()}</section><section class="panel"><div class="panel-head"><div><h2>最近活动</h2><span>事件流</span></div></div>${eventList()}</section></div><section class="panel"><div class="panel-head"><div><h2>最新产物</h2><span>来自比赛目录的登记文件</span></div><button class="subtle-btn" data-view="experiments">打开结果 →</button></div><div class="artifact-row">${artifacts().slice(0,6).map(a=>{const x=typeof a==='string'?{path:a}:a;return `<button class="artifact-chip" data-file="${esc(x.id||x.path)}"><span>${esc(pathParts(x.path).slice(-1)[0]||x.name)}</span><small>${esc(x.kind||x.type||'artifact')}</small></button>`}).join('')||'<div class="empty">暂无登记产物</div>'}</div></section>`;}
  function renderWorkflow(){document.getElementById('app').innerHTML=`<div class="page-title"><div><span class="eyebrow">WORKSPACE / WORKFLOW</span><h1>S0–S8 建模流程</h1><p>每个阶段都必须由 Guard 给出验证依据。</p></div></div><section class="panel">${stageTable()}</section><section class="panel"><div class="panel-head"><div><h2>活动记录</h2><span>人工事件不会授予 PASS</span></div></div>${eventList()}</section>`;}
  function renderExperiments(){const jobs=Array.isArray(state.jobs)?state.jobs:[];document.getElementById('app').innerHTML=`<div class="page-title"><div><span class="eyebrow">WORKSPACE / RUNS</span><h1>实验结果</h1><p>保留参数、日志、指标和原始科学产物。</p></div></div><section class="panel"><div class="panel-head"><div><h2>运行记录</h2><span>${jobs.length} 个任务</span></div></div>${jobs.length?jobs.map(j=>`<div class="job-line"><span class="job-type">${esc(j.type||j.name||'model run')}</span><span class="mono">${esc(j.id||'')}</span><span class="job-time">${fmt(j.started_at)}</span>${badge(j.status)}</div>`).join(''):'<div class="empty">暂无可比较实验<br><span>运行受控模型任务后，参数与指标会在此保留。</span></div>'}</section><section class="panel"><div class="panel-head"><div><h2>图表与结果文件</h2><span>不填充示例数据</span></div></div><div class="artifact-row">${artifacts().filter(a=>/figure|chart|table|result/i.test((a.path||a.kind||''))).map(a=>`<button class="artifact-chip" data-file="${esc(a.id||a.path)}">${esc(a.path||a.name)}</button>`).join('')||'<div class="empty">没有结果产物</div>'}</div></section>`;}
  function renderCode(){document.getElementById('app').innerHTML=`<div class="page-title"><div><span class="eyebrow">WORKSPACE / CODE</span><h1>代码与日志</h1><p>只读查看生成代码，运行任务在本地项目中执行。</p></div></div><div class="split-grid"><section class="panel panel-wide"><div class="panel-head"><div><h2>文件预览</h2><span>选择左侧文件树中的代码文件</span></div></div>${filePreview()}</section><section class="panel"><div class="panel-head"><div><h2>运行日志</h2><span>stdout / stderr</span></div></div><pre class="log-block">${esc(state.logs||state.log||'暂无日志')}</pre></section></div>`;}
  function renderDelivery(){document.getElementById('app').innerHTML=`<div class="page-title"><div><span class="eyebrow">WORKSPACE / DELIVERY</span><h1>论文与交付</h1><p>论文写作在 Codex 对话完成，工作台负责证据与格式检查。</p></div></div><section class="panel"><div class="panel-head"><div><h2>交付产物</h2><span>Markdown · PDF · Word</span></div></div><div class="artifact-row">${artifacts().filter(a=>/paper|pdf|docx|document/i.test((a.path||a.kind||''))).map(a=>`<button class="artifact-chip" data-file="${esc(a.id||a.path)}">${esc(a.path||a.name)}</button>`).join('')||'<div class="empty">暂无论文交付文件</div>'}</div></section>`;}
  function render(){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===view));({overview:renderOverview,workflow:renderWorkflow,experiments:renderExperiments,code:renderCode,delivery:renderDelivery}[view]||renderOverview)();renderTree();renderInspector();}
  function renderInspector(){const g=state.guard||{};const passed=state.stages.filter(x=>x.status==='passed').length;document.getElementById('guard-summary').innerHTML=`<div class="guard-score"><strong>${passed}</strong><span>/ 9 阶段已验证</span></div><div class="guard-bar"><i style="width:${passed/9*100}%"></i></div><div class="guard-status">${esc(g.status||'等待检查')}</div>`;const task=state.current_task||'等待 Codex';document.getElementById('inspector-task').innerHTML=`<span class="task-state ${state.status==='running'?'busy':''}"></span><div><strong>${esc(task)}</strong><p>${esc(state.message||'在对话中说“开始建模”')}</p></div>`;document.getElementById('side-log').innerHTML=eventList();document.getElementById('next-action').textContent=state.next_action||state.recommended_action||'等待 Guard 建议';}
  async function refresh(){try{const [sr,er]=await Promise.all([fetch(api('/api/status'),{cache:'no-store'}),fetch(api('/api/events'),{cache:'no-store'})]);if(!sr.ok)throw Error(sr.status);const incoming=await sr.json();let history=incoming.history||[];const txt=await er.text();if(txt.trim()){try{const j=JSON.parse(txt);history=Array.isArray(j)?j:history;}catch{history=txt.split(/\r?\n/).map(x=>{try{return JSON.parse(x)}catch{return null}}).filter(Boolean)}}state={...state,...incoming,history};state.stages=normalize(state);document.getElementById('project-name').textContent=state.project||'MathModel project';document.getElementById('project-path').textContent=state.project_root||'比赛项目目录';document.getElementById('connection-label').innerHTML='<i id="connection-dot" class="online"></i>已连接';document.getElementById('last-sync').textContent=`同步于 ${fmt(new Date().toISOString())}`;render();}catch(e){document.getElementById('connection-label').innerHTML='<i id="connection-dot" class="offline"></i>服务断开';if(!state.stages.length){state.stages=normalize(state);render();}}}
  document.getElementById('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;render();}});document.getElementById('app').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;render();}const f=e.target.closest('[data-file]');if(f)openArtifact(f.dataset.file);});document.getElementById('file-tree').addEventListener('click',e=>{const f=e.target.closest('[data-file]');if(f)openArtifact(f.dataset.file);});document.getElementById('refresh-button').addEventListener('click',refresh);document.getElementById('run-check').addEventListener('click',async e=>{const old=e.target.textContent;e.target.disabled=true;e.target.textContent='检查中…';try{const r=await fetch(api('/api/jobs'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'preflight'})});if(!r.ok)throw Error(r.status);e.target.textContent='已提交';refresh();}catch{e.target.textContent='提交失败';}setTimeout(()=>{e.target.disabled=false;e.target.textContent=old;},1400);});document.getElementById('copy-next').addEventListener('click',async e=>{try{await navigator.clipboard.writeText(state.next_action||'请告诉我下一步建模动作。');e.target.textContent='已复制';setTimeout(()=>e.target.textContent='复制到对话',1200);}catch{e.target.textContent='请手动复制';}});document.getElementById('theme-toggle').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light';});document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea'))return;const views=['overview','workflow','experiments','code','delivery'];if(/^\d$/.test(e.key)&&views[+e.key-1]){view=views[+e.key-1];render();}});state.stages=normalize(state);render();refresh();setInterval(refresh,3000);
})();
