/* MathModel Workbench: dependency-free UI bundle. Data comes from the local service only. */
(() => {
  const STAGES = ['S0','S1','S2','S3','S4','S5','S6','S7','S8'];
  const TITLES = { S0:'输入接纳', S1:'问题分析', S2:'模型路线', S3:'数据与可视化', S4:'可复现代码', S5:'真实执行', S6:'证据门禁', S7:'正式写作', S8:'格式与渲染检查' };
  const STATUS_LABELS = { pending:'待执行', running:'运行中', passed:'已通过', failed:'失败', stale:'已失效', validating:'待验证' };
  const VIEW_TITLES = { overview:'概览', workflow:'建模流程', experiments:'实验结果', code:'代码与日志', delivery:'论文与交付' };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const root = document.documentElement;
  const app = document.getElementById('app');
  let view = 'overview'; let state = emptyState(); let connected = false;
  const token = new URLSearchParams(location.search).get('token') || '';
  const api = path => `${path}${path.includes('?') ? '&' : '?'}token=${encodeURIComponent(token)}`;
  function emptyState() { return { project:'MathModel project', stage:'S0', status:'pending', message:'还没有记录建模状态。请在对话中说“开始建模”。', artifacts:[], history:[], stages:[] }; }
  function normalizeStages(s) {
    if (Array.isArray(s.stages) && s.stages.length) return STAGES.map(code => {
      const item = s.stages.find(x => x.code === code || x.stage === code) || {};
      return { code, name:TITLES[code], status:item.status || 'pending', message:item.message || '', updated_at:item.updated_at };
    });
    const current = s.stage || 'S0'; const idx = STAGES.indexOf(current);
    return STAGES.map((code, i) => ({ code, name:TITLES[code], status: i < idx ? 'passed' : (i === idx ? (s.status || 'pending') : 'pending'), message:i === idx ? (s.message || '') : '' }));
  }
  function statusBadge(status) { const safe = ['running','passed','failed','stale','pending','validating'].includes(status) ? status : 'pending'; return `<span class="badge badge-${safe}">${esc(STATUS_LABELS[safe] || safe)}</span>`; }
  function card(title, content, cls='col-6', subtitle='') { return `<section class="card ${cls}"><div class="card-header"><div><h2 class="card-title">${title}</h2>${subtitle ? `<p class="card-subtitle">${subtitle}</p>` : ''}</div></div>${content}</section>`; }
  function formatTime(value, withDate=false) { if (!value) return '—'; const d = new Date(value); if (Number.isNaN(d.getTime())) return esc(value); return d.toLocaleString('zh-CN', withDate ? {month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'} : {hour:'2-digit',minute:'2-digit',second:'2-digit'}); }
  function artifactInfo(item) { if (typeof item === 'string') return {path:item, label:item, kind:'产物'}; return {path:item.path || item.url || '', label:item.name || item.path || item.id || '未命名产物', kind:item.kind || item.type || '产物', id:item.id}; }
  function artifactsMarkup(list) { if (!Array.isArray(list) || !list.length) return `<div class="empty"><div><strong>还没有登记的产物</strong>模型运行、图表和论文文件会在验证后出现在这里。</div></div>`; return `<div class="artifact-grid">${list.map(raw => { const a=artifactInfo(raw); const href = a.id ? api(`/api/artifacts/${encodeURIComponent(a.id)}`) : '#'; return `<a class="artifact" href="${esc(href)}" target="_blank" rel="noreferrer"><span class="artifact-name">${esc(a.label)}</span><span class="artifact-type">${esc(a.kind)}</span></a>`; }).join('')}</div>`; }
  function eventsMarkup(events) { if (!events.length) return `<div class="empty"><div><strong>暂无活动记录</strong>完成一次预检或运行后，这里会显示可追溯事件。</div></div>`; return `<div class="event-list">${events.slice().reverse().slice(0,30).map(e => `<div class="event-row"><span class="event-stage">${esc(e.stage || '—')}</span><div><strong>${esc(STATUS_LABELS[e.status] || e.status || '活动')}</strong><p class="event-message">${esc(e.message || e.current_task || '未提供说明')}</p></div><time class="event-time">${formatTime(e.timestamp)}</time></div>`).join('')}</div>`; }
  function stageRows(stages, expanded=false) { return `<div class="stage-list">${stages.map(x => `<div class="stage-row"><span class="stage-code">${x.code}</span><div><div class="stage-name">${esc(x.name)}</div>${expanded && x.message ? `<div class="stage-detail">${esc(x.message)}</div>` : ''}</div>${statusBadge(x.status)}</div>`).join('')}</div>`; }
  function currentStage() { const s = state.stage || 'S0'; return { code:s, name:TITLES[s] || '建模阶段', status:state.status || 'pending' }; }
  function verifiedCount() { return state.stages.filter(x => x.status === 'passed').length; }
  function renderOverview() {
    const c=currentStage(); const blocked = state.blocked_reason || state.blocking_reason || (c.status === 'failed' ? state.message : '');
    app.innerHTML = `<div class="grid"><section class="card hero-card col-8"><div class="hero-line"><div><p class="eyebrow">当前工作状态</p><h2 class="hero-stage">${c.code} · ${esc(c.name)}</h2><p class="hero-message">${esc(state.message || '等待 Codex 在对话中推进下一步。')}</p></div>${statusBadge(c.status)}</div><div class="stat-row"><div class="stat"><span class="stat-value">${verifiedCount()} / 9</span><span class="stat-label">已验证阶段</span></div><div class="stat"><span class="stat-value">${state.current_task ? esc(state.current_task) : '—'}</span><span class="stat-label">当前任务</span></div><div class="stat"><span class="stat-value">${state.updated_at ? formatTime(state.updated_at) : '—'}</span><span class="stat-label">最近更新</span></div></div></section>${card('下一步', `<div class="notice">${esc(state.next_action || state.recommended_action || '请在对话中询问 Codex 下一步建模动作。')}</div><div style="margin-top:12px"><button class="button secondary" data-action="copy-next">复制建议到对话</button></div>`, 'col-4', '由 Workflow Guard 提供')} ${blocked ? card('需要处理', `<div class="notice">${esc(blocked)}</div>`, 'col-12', '验证阻塞') : ''} ${card('建模流程', stageRows(state.stages.slice(0,9)), 'col-8', 'S0–S8 · 状态来自验证结果')} ${card('最近活动', eventsMarkup(state.history), 'col-4', '本地事件记录')} ${card('最新产物', artifactsMarkup(state.artifacts), 'col-12', '仅显示已登记文件')}</div>`;
  }
  function renderWorkflow() { app.innerHTML = `<div class="grid">${card('S0–S8 建模流程', stageRows(state.stages, true), 'col-8', '每个状态均需有验证依据')} ${card('阶段说明', `<div class="notice">${esc(state.message || '选择一个阶段查看其输入、输出和验证依据。')}</div><dl class="details"><dt>当前阶段</dt><dd>${esc((state.stage || 'S0') + ' · ' + (TITLES[state.stage] || ''))}</dd><dt>验证状态</dt><dd>${statusBadge(state.status || 'pending')}</dd><dt>当前任务</dt><dd>${esc(state.current_task || '—')}</dd></dl>`, 'col-4', '状态快照')} ${card('活动记录', eventsMarkup(state.history), 'col-12', '活动描述不会授予 PASS')}</div>`; }
  function renderExperiments() { const jobs = Array.isArray(state.jobs) ? state.jobs : []; const metrics = Array.isArray(state.metrics) ? state.metrics : []; const jobContent = jobs.length ? jobs.map(j => `<div class="job-row"><div class="job-meta"><span class="job-name">${esc(j.name || j.type || '模型任务')}</span><span class="job-id">${esc(j.id || '')}</span></div>${statusBadge(j.status || 'pending')}</div>`).join('') : `<div class="empty"><div><strong>暂无可比较实验</strong>运行受控模型任务后，参数与指标会在此保留。</div></div>`; const metricContent = metrics.length ? `<div class="artifact-grid">${metrics.map(m => `<div class="artifact"><span class="artifact-name">${esc(m.name || m.key)}</span><span class="artifact-type">${esc(m.value ?? '—')} ${esc(m.unit || '')}</span></div>`).join('')}</div>` : `<div class="empty"><div><strong>没有指标数据</strong>看板不会用示例数字填充结果。</div></div>`; app.innerHTML = `<div class="grid">${card('运行记录', jobContent, 'col-8', '失败与取消的日志仍会保留')} ${card('指标对比', metricContent, 'col-4', '真实运行结果')} ${card('图表与结果文件', artifactsMarkup(state.artifacts.filter(x => ['figure','chart','table','result'].includes(artifactInfo(x).kind))), 'col-12', '原始科学产物')}</div>`; }
  function renderCode() { const logs = state.logs || state.log || ''; const source = state.code_preview || ''; app.innerHTML = `<div class="grid">${card('代码预览', source ? `<pre class="code-block">${esc(source)}</pre>` : `<div class="empty"><div><strong>没有登记代码预览</strong>请通过产物接口登记运行代码。</div></div>`, 'col-8', '只读 · 来源由产物登记')} ${card('运行日志', logs ? `<pre class="code-block">${esc(logs)}</pre>` : `<div class="empty"><div><strong>暂无日志</strong>启动受控任务后，标准输出和错误会显示在此。</div></div>`, 'col-4', 'stdout / stderr')} ${card('运行状态', `<div class="details"><dt>任务</dt><dd>${esc(state.current_task || '—')}</dd><dt>退出状态</dt><dd>${esc(state.exit_code ?? '—')}</dd><dt>耗时</dt><dd>${esc(state.duration_ms != null ? `${state.duration_ms} ms` : '—')}</dd></div>`, 'col-12', '本地进程')}</div>`; }
  function renderDelivery() { const chapters = Array.isArray(state.chapters) ? state.chapters : []; const chapterContent = chapters.length ? stageRows(chapters.map(c => ({code:c.code || c.id || '—', name:c.name || c.title || '章节', status:c.status || 'pending', message:c.message})), true) : `<div class="empty"><div><strong>暂无章节状态</strong>论文写作由 Codex 对话完成，完成后登记章节证据。</div></div>`; app.innerHTML = `<div class="grid">${card('论文章节', chapterContent, 'col-8', '正式写作与证据关联')} ${card('交付检查', `<div class="notice">${esc(state.delivery_message || state.format_message || '格式与渲染检查尚未运行。')}</div><div style="margin-top:12px">${statusBadge(state.delivery_status || 'pending')}</div>`, 'col-4', 'Word / PDF')} ${card('交付产物', artifactsMarkup(state.artifacts.filter(x => ['paper','pdf','docx','document'].includes(artifactInfo(x).kind))), 'col-12', 'Markdown、PDF、Word')}</div>`; }
  function render() { document.getElementById('view-title').textContent=VIEW_TITLES[view]; document.querySelectorAll('.nav-item').forEach(b => b.classList.toggle('active', b.dataset.view===view)); ({overview:renderOverview,workflow:renderWorkflow,experiments:renderExperiments,code:renderCode,delivery:renderDelivery}[view] || renderOverview)(); }
  async function refresh() { try { const responses=await Promise.all([fetch(api('/api/status'),{cache:'no-store'}),fetch(api('/api/events'),{cache:'no-store'})]); if (!responses[0].ok) throw new Error(`HTTP ${responses[0].status}`); const incoming=await responses[0].json(); let history=Array.isArray(incoming.history) ? incoming.history : []; const eventText=await responses[1].text(); if (eventText.trim()) { try { const parsed=JSON.parse(eventText); if (Array.isArray(parsed)) history=parsed; } catch { history=eventText.trim().split(/\r?\n/).map(line=>{try{return JSON.parse(line)}catch{return null}}).filter(Boolean); } } state={...emptyState(),...incoming,history}; state.stages=normalizeStages(state); connected=true; document.getElementById('connection-dot').className='status-dot online'; document.getElementById('connection-label').textContent='本地服务已连接'; document.getElementById('last-sync').textContent=`同步于 ${formatTime(new Date().toISOString())}`; document.getElementById('project-name').textContent=state.project || 'MathModel project'; document.getElementById('project-path').textContent=state.project_root || ''; render(); } catch (error) { connected=false; document.getElementById('connection-dot').className='status-dot offline'; document.getElementById('connection-label').textContent='服务断开'; document.getElementById('last-sync').textContent='无法读取本地状态'; if (!state.updated_at) { state=emptyState(); state.stages=normalizeStages(state); render(); } } }
  document.getElementById('nav-list').addEventListener('click', e => { const button=e.target.closest('[data-view]'); if (button) { view=button.dataset.view; render(); } });
  document.addEventListener('keydown', e => { if (e.defaultPrevented || e.ctrlKey || e.metaKey || e.altKey || e.target.closest('input,textarea,select,[contenteditable="true"]')) return; const views=['overview','workflow','experiments','code','delivery']; const index=Number(e.key)-1; if (index>=0 && index<views.length) { view=views[index]; render(); } });
  document.getElementById('refresh-button').addEventListener('click', refresh);
  document.getElementById('theme-toggle').addEventListener('click', () => { const next=root.dataset.theme==='dark'?'light':'dark'; root.dataset.theme=next; try{localStorage.setItem('mathmodel-theme',next)}catch{} });
  app.addEventListener('click', async e => { if (e.target.closest('[data-action="copy-next"]')) { const text=state.next_action || state.recommended_action || '请告诉我下一步建模动作。'; try { await navigator.clipboard.writeText(text); e.target.textContent='已复制'; setTimeout(()=>e.target.textContent='复制建议到对话',1600); } catch { e.target.textContent='请手动复制对话建议'; } } });
  try { const saved=localStorage.getItem('mathmodel-theme'); if(saved) root.dataset.theme=saved; } catch {}
  state.stages=normalizeStages(state); render(); refresh(); setInterval(refresh, 3000);
})();
